package enums;

public enum Servico {
    TROCA_OLEO,
    ALINHAMENTO,
    TROCA_PNEUS,
    REVISAO_GERAL,
    TROCA_PASTILHA_FREIO,
    TROCA_FILTROS,
    LIMPEZA_AR_CONDICIONADO,
    TROCA_BATERIA,
    POLIMENTO,
    LAVAGEM_COMPLETA,
    REPARO_SUSPENSAO,
    DIAGNOSTICO_ELETRONICO,
    TROCA_CORREIA_DENTADA,
    REPARO_LATARIA,
    PINTURA_VEICULO
}

